//! Argon minimal-cover conformance vectors at every CPU level.
//!
//! `tests/argon_cover_manifest.tsv` (generated by `scripts/argon_cover_select.py`)
//! lists a greedy minimal set of official Argon streams whose union covers
//! **every testPoint** in the AOM coverage reports (`prof_av1_profile*.xml`) —
//! 61 streams covering 18,588 spec items. Streams are fetched lazily into
//! `test-vectors/argon_subset/` (see `argon_vectors::ensure_argon_cover_stream`);
//! nothing is committed.
//!
//! Each stream is decoded twice — `apply_grain=false` pinned against the
//! suite's `md5_no_film_grain` sidecar, `apply_grain=true` against `md5_ref` —
//! at every `CpuLevel::platform_levels()`. Any per-level divergence means a
//! non-bit-exact SIMD kernel (the defect class this gate exists for).
//!
//! `rav1d_set_cpu_flags_mask` is process-global: the level mask is set per
//! decode, so all decodes run under `CPU_LEVEL_LOCK` (same pattern as
//! `decode_cpu_levels.rs`).

// 93 MB of streams × 2 passes × N levels in a dev profile is far too slow —
// same reason decode_cpu_levels is release-gated.
#[cfg(debug_assertions)]
compile_error!("argon_cover requires release mode: cargo test --release --test argon_cover");

use rav1d_safe::src::managed::{CpuLevel, Decoder, Settings, Strictness};
use std::path::PathBuf;
use std::sync::Mutex;

#[path = "../examples/helpers/annexb_parser.rs"]
mod annexb_parser;
#[path = "common/argon_vectors.rs"]
mod argon_vectors;
#[path = "common/committed_vectors.rs"]
#[allow(dead_code)]
mod committed_vectors;
#[allow(dead_code)]
mod ivf_parser;

use committed_vectors::hash_frame;

static CPU_LEVEL_LOCK: Mutex<()> = Mutex::new(());

enum Format {
    Ivf,
    AnnexB,
    RawObu,
}

fn detect_format(data: &[u8]) -> Format {
    if data.len() >= 4 && &data[0..4] == b"DKIF" {
        return Format::Ivf;
    }
    if data.is_empty() {
        return Format::RawObu;
    }
    let first = data[0];
    let forbidden = (first >> 7) & 1;
    let obu_type = (first >> 3) & 0xF;
    let has_size = (first >> 1) & 1;
    if forbidden == 0 && matches!(obu_type, 1..=8 | 15) && has_size == 1 {
        Format::RawObu
    } else {
        Format::AnnexB
    }
}

fn decode_unit(
    decoder: &mut Decoder,
    data: &[u8],
    ctx: &mut md5::Context,
    errors: &mut Vec<String>,
) {
    match decoder.decode(data) {
        Ok(Some(frame)) => hash_frame(&frame, ctx),
        Ok(None) => {}
        Err(e) => {
            errors.push(format!("decode error: {e}"));
            return;
        }
    }
    loop {
        match decoder.get_frame() {
            Ok(Some(frame)) => hash_frame(&frame, ctx),
            Ok(None) => break,
            Err(e) => {
                errors.push(format!("drain error: {e}"));
                break;
            }
        }
    }
}

/// Decode `data` (IVF / Annex B / raw OBU) at `level`, hash all shown frames.
/// Returns (md5, decode errors) — errors are reported separately so "decoder
/// rejected a conformant stream" doesn't masquerade as a pixel mismatch.
fn decode_md5_at(data: &[u8], level: CpuLevel, grain: bool) -> (String, Vec<String>) {
    let _guard = CPU_LEVEL_LOCK.lock().unwrap();
    let mut settings = Settings::default();
    // Lenient = dav1d conceal-and-continue parity — same flag the Argon
    // sidecar MD5s were generated under.
    settings.strictness = Strictness::Lenient;
    settings.threads = 1;
    settings.max_frame_delay = 1;
    settings.frame_size_limit = 8192 * 8192;
    settings.cpu_level = level;
    settings.apply_grain = grain;
    let mut decoder = Decoder::with_settings(settings).expect("decoder");
    let mut ctx = md5::Context::new();
    let mut errors = Vec::new();

    match detect_format(data) {
        Format::Ivf => {
            let mut cursor = std::io::Cursor::new(data);
            for frame in &ivf_parser::parse_all_frames(&mut cursor).expect("ivf parse") {
                decode_unit(&mut decoder, &frame.data, &mut ctx, &mut errors);
            }
        }
        Format::AnnexB => match annexb_parser::parse_annexb(data) {
            Ok(units) => {
                for unit in &units {
                    decode_unit(&mut decoder, &unit.data, &mut ctx, &mut errors);
                }
            }
            Err(e) => errors.push(format!("annexb parse: {e}")),
        },
        Format::RawObu => decode_unit(&mut decoder, data, &mut ctx, &mut errors),
    }

    match decoder.flush() {
        Ok(remaining) => {
            for f in &remaining {
                hash_frame(f, &mut ctx);
            }
        }
        Err(e) => errors.push(format!("flush error: {e}")),
    }
    (format!("{:x}", ctx.finalize()), errors)
}

#[test]
fn argon_cover_streams_bit_exact_across_levels() {
    let manifest = argon_vectors::argon_cover_manifest();
    let levels = CpuLevel::platform_levels();
    eprintln!(
        "argon cover: {} streams × {} levels × 2 grain passes",
        manifest.len(),
        levels.len()
    );

    let mut failures = Vec::new();
    for e in &manifest {
        let path: PathBuf = argon_vectors::ensure_argon_cover_stream(e);
        let data = std::fs::read(&path).unwrap_or_else(|err| panic!("read {path:?}: {err}"));
        for &level in levels {
            for (grain, expected) in [(false, &e.md5_nofg), (true, &e.md5_ref)] {
                let Some(expected) = expected else { continue };
                let (got, errors) = decode_md5_at(&data, level, grain);
                if !errors.is_empty() {
                    failures.push(format!(
                        "{} [{level} grain={grain}]: {}",
                        e.relpath,
                        errors.join("; ")
                    ));
                } else if got != *expected {
                    failures.push(format!(
                        "{} [{level} grain={grain}]: expected {expected}, got {got}",
                        e.relpath
                    ));
                }
            }
        }
        eprintln!("ok {}", e.relpath);
    }
    assert!(
        failures.is_empty(),
        "{} Argon cover-stream divergences:\n{}",
        failures.len(),
        failures.join("\n")
    );
}
