use std::path::{Path, PathBuf};

// ---------------------------------------------------------------------------
// Argon cover subset — lazily-fetched conformance vectors.
//
// `tests/argon_cover_manifest.tsv` (generated by scripts/argon_cover_select.py)
// lists a minimal set of streams whose union covers every testPoint in the
// official Argon coverage reports (prof_av1_profile{0,1,2}.xml). The streams
// themselves are NOT committed — the suite carries a Broadcom/Argon "all
// rights reserved" header, and 93 MB of bitstreams does not belong in git —
// they are fetched into `test-vectors/argon_subset/` on first use.
//
// Fetch order, first hit wins:
//   1. the local cache itself,
//   2. a full extracted suite at test-vectors/argon/<release-dir>/
//      (what CI's prep-argon job produces — zero network),
//   3. ARGON_COVER_BASE_URL — a per-file URL prefix (e.g. an R2 mirror that
//      stores the extracted tree): GET <base>/<relpath>,
//   4. ARGON_COVER_ZIP_URL (default: the canonical S3 release zip) — an HTTP
//      range GET at the member's stored data offset + raw-DEFLATE inflate.

/// One row of `tests/argon_cover_manifest.tsv`.
pub struct ArgonCoverEntry {
    /// Path inside the extracted suite, e.g. `profile0_core/streams/testN.obu`.
    pub relpath: String,
    /// Byte offset of the member's compressed data inside the canonical zip.
    pub data_off: u64,
    /// Compressed size in the zip.
    pub csize: u64,
    /// Uncompressed size — used as the cache-validity check.
    pub usize_: u64,
    /// Zip compression method (0 = stored, 8 = deflate).
    pub method: u16,
    /// md5_no_film_grain sidecar (None when the release ships none).
    pub md5_nofg: Option<String>,
    /// md5_ref sidecar (film grain applied).
    pub md5_ref: Option<String>,
}

/// Parse the committed cover manifest.
pub fn argon_cover_manifest() -> Vec<ArgonCoverEntry> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/argon_cover_manifest.tsv");
    let text =
        std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("cannot read {path:?}: {e}"));
    let mut out = Vec::new();
    for line in text.lines() {
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let f: Vec<&str> = line.split('\t').collect();
        assert_eq!(f.len(), 7, "malformed manifest line: {line:?}");
        let md5 = |s: &str| (s != "-").then(|| s.to_string());
        out.push(ArgonCoverEntry {
            relpath: f[0].to_string(),
            data_off: f[1].parse().expect("data_off"),
            csize: f[2].parse().expect("csize"),
            usize_: f[3].parse().expect("usize"),
            method: f[4].parse().expect("method"),
            md5_nofg: md5(f[5]),
            md5_ref: md5(f[6]),
        });
    }
    out
}

const ARGON_ZIP_URL: &str = "https://aom-cwg-av1-argon-streams-public.s3.us-east-1.amazonaws.com/argon_coveragetool_av1_base_and_extended_profiles_v2.1.1.zip";

fn curl_to(url: &str, dest: &Path, range: Option<(u64, u64)>) -> bool {
    let staging = dest.with_extension(format!("tmp.{}", std::process::id()));
    let mut cmd = std::process::Command::new("curl");
    cmd.args(["-sSfL", "-o"]);
    cmd.arg(&staging);
    if let Some((a, b)) = range {
        cmd.arg("--range").arg(format!("{a}-{b}"));
    }
    let ok = cmd.arg(url).status().map(|s| s.success()).unwrap_or(false);
    if ok {
        // As in ensure_dav1d_test_data: rename races are benign; keep the
        // winner's copy.
        if std::fs::rename(&staging, dest).is_err() {
            let _ = std::fs::remove_file(&staging);
        }
        return true;
    }
    let _ = std::fs::remove_file(&staging);
    false
}

/// Fetch (or reuse) one cover-set stream; returns its path.
///
/// Panics if the stream cannot be obtained — a missing fetch is an
/// environment bug, not a skip, same convention as `ensure_dav1d_test_data`.
pub fn ensure_argon_cover_stream(e: &ArgonCoverEntry) -> PathBuf {
    let cache = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("test-vectors/argon_subset")
        .join(&e.relpath);

    if cache.exists() {
        if std::fs::metadata(&cache).map(|m| m.len()).ok() == Some(e.usize_) {
            return cache;
        }
        let _ = std::fs::remove_file(&cache); // truncated/stale
    }

    // 2. full extracted suite already on disk (CI prep-argon / local dev)
    let suites_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("test-vectors/argon");
    if let Ok(rd) = std::fs::read_dir(&suites_dir) {
        for ent in rd.flatten() {
            let cand = ent.path().join(&e.relpath);
            // Same-named streams differ across suite releases — only reuse a
            // local extract whose member size matches the manifest exactly.
            if cand.is_file() && std::fs::metadata(&cand).map(|m| m.len()).ok() == Some(e.usize_) {
                if let Some(p) = cache.parent() {
                    std::fs::create_dir_all(p).unwrap();
                }
                std::fs::copy(&cand, &cache).unwrap_or_else(|err| panic!("copy {cand:?}: {err}"));
                return cache;
            }
        }
    }

    if let Some(p) = cache.parent() {
        std::fs::create_dir_all(p).unwrap();
    }

    // 3. per-file mirror
    if let Ok(base) = std::env::var("ARGON_COVER_BASE_URL") {
        let url = format!("{}/{}", base.trim_end_matches('/'), e.relpath);
        if curl_to(&url, &cache, None) {
            return cache;
        }
    }

    // 4. range-fetch from the canonical zip
    let zip = std::env::var("ARGON_COVER_ZIP_URL").unwrap_or_else(|_| ARGON_ZIP_URL.into());
    let staging = cache.with_extension(format!("deflate.{}", std::process::id()));
    assert!(
        curl_to(&zip, &staging, Some((e.data_off, e.data_off + e.csize - 1))),
        "range fetch failed for {} from {zip}",
        e.relpath
    );
    let raw = std::fs::read(&staging).unwrap();
    let _ = std::fs::remove_file(&staging);
    let data = match e.method {
        0 => raw,
        8 => miniz_oxide::inflate::decompress_to_vec(&raw)
            .unwrap_or_else(|r| panic!("inflate {}: {r:?}", e.relpath)),
        m => panic!("unsupported zip method {m} for {}", e.relpath),
    };
    assert_eq!(
        data.len() as u64,
        e.usize_,
        "size mismatch inflating {}",
        e.relpath
    );
    std::fs::write(&cache, &data).unwrap();
    cache
}
