#!/usr/bin/env bash
# Argon conformance-suite MD5 verification for rav1d-safe.
#
# Usage: argon_md5_check.sh <argon_root> <decode_md5_binary> [max_streams]
#
#   <argon_root>        Directory containing the per-profile folders
#                       (profile0_core/, profile1_core/, ...), each with
#                       streams/, md5_ref/, and md5_no_film_grain/.
#   <decode_md5_binary> Path to a built `decode_md5` example binary.
#   [max_streams]       Optional cap on streams tested (0 = all).
#
# The Argon reference hashes are generated by a dav1d-semantics decoder, so
# verification runs with --lenient (conceal-and-continue) — four synthesized
# coverage streams carry deliberately non-conforming segment_ids that the
# default Strictness::Strict correctly rejects. Strict-mode rejections are
# still counted and listed as informational output.
#
# Each stream is checked twice: once without film grain against
# md5_no_film_grain/, and once with --filmgrain against md5_ref/.

set -u

ARGON_ROOT="${1:?usage: argon_md5_check.sh <argon_root> <decode_md5_binary> [max_streams]}"
BIN="${2:?usage: argon_md5_check.sh <argon_root> <decode_md5_binary> [max_streams]}"
MAX="${3:-0}"
JOBS="${ARGON_JOBS:-$(nproc)}"

if [ ! -x "$BIN" ]; then
    echo "decode_md5 binary not found/executable: $BIN" >&2
    exit 2
fi
if [ ! -d "$ARGON_ROOT" ]; then
    echo "argon root not found: $ARGON_ROOT" >&2
    exit 2
fi

WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT

check_one() {
    stream="$1"
    prof_dir="$(dirname "$(dirname "$stream")")"
    name="$(basename "$stream" .obu)"
    bin="$BIN"

    # No-film-grain pass
    if [ -f "$prof_dir/md5_no_film_grain/$name.md5" ]; then
        exp="$(cut -d' ' -f1 < "$prof_dir/md5_no_film_grain/$name.md5")"
        if out="$("$bin" --lenient -q "$stream" "$exp" 2>&1)"; then
            echo "PASS nofg $stream"
        else
            echo "FAIL nofg $stream :: $(echo "$out" | tail -1)"
        fi
    else
        echo "SKIP nofg $stream (no sidecar)"
    fi

    # Film-grain pass
    if [ -f "$prof_dir/md5_ref/$name.md5" ]; then
        exp="$(cut -d' ' -f1 < "$prof_dir/md5_ref/$name.md5")"
        if out="$("$bin" --lenient --filmgrain -q "$stream" "$exp" 2>&1)"; then
            echo "PASS grain $stream"
        else
            echo "FAIL grain $stream :: $(echo "$out" | tail -1)"
        fi
    else
        echo "SKIP grain $stream (no sidecar)"
    fi

    # Informational: does the default Strict mode reject this stream?
    # (decode_md5 exits 0 on decoder errors, so inspect stderr.)
    strict_out="$("$bin" -q "$stream" 2>&1)"
    if echo "$strict_out" | grep -q "Decode error\|Flush error"; then
        echo "INFO strict-reject $stream"
    else
        echo "INFO strict-ok $stream"
    fi
}
export -f check_one
export BIN

mapfile -t STREAMS < <(find "$ARGON_ROOT" -path '*/streams/*.obu' | sort)
if [ "$MAX" -gt 0 ] && [ "${#STREAMS[@]}" -gt "$MAX" ]; then
    STREAMS=("${STREAMS[@]:0:$MAX}")
fi

TOTAL=${#STREAMS[@]}
echo "Checking $TOTAL Argon streams (grain + no-grain) with $JOBS jobs..."

printf '%s\n' "${STREAMS[@]}" | xargs -P "$JOBS" -I{} bash -c 'check_one "$@"' _ {} \
    > "$WORKDIR/results.txt" 2>"$WORKDIR/err.txt"

PASS=$(grep -c '^PASS' "$WORKDIR/results.txt" || true)
FAIL=$(grep -c '^FAIL' "$WORKDIR/results.txt" || true)
SKIP=$(grep -c '^SKIP' "$WORKDIR/results.txt" || true)
STRICT_REJECTS=$(grep -c '^INFO strict-reject' "$WORKDIR/results.txt" || true)

echo
echo "=== Results ==="
echo "PASS: $PASS"
echo "FAIL: $FAIL"
echo "SKIP: $SKIP"
echo "Strict-mode rejections (informational, expected on ~4 non-conforming streams): $STRICT_REJECTS"

if [ "$FAIL" -gt 0 ]; then
    echo
    echo "=== Failures ==="
    grep '^FAIL' "$WORKDIR/results.txt"
fi
if [ "$STRICT_REJECTS" -gt 0 ]; then
    echo
    echo "=== Strict-mode rejections (informational) ==="
    grep '^INFO strict-reject' "$WORKDIR/results.txt"
fi
if [ -s "$WORKDIR/err.txt" ]; then
    echo
    echo "=== stderr (first 20 lines) ==="
    head -20 "$WORKDIR/err.txt"
fi

[ "$FAIL" -eq 0 ]
