#!/bin/bash
# Regenerate the owned conformance corpus under tests/gen_vectors/.
#
# Where the Argon suite covers the AV1 syntax space with directed random
# streams, this script covers the decoder-facing *feature* space with a fixed
# owned matrix: zenav1-svt's `gen_cover` example encodes deterministic
# synthetic content under controlled configs (bit depths, chroma formats,
# tiles, superres, film grain, sb sizes, preset/qp extremes, intra + flat
# low-delay P inter with synthetic motion). The streams are ours — they are
# committed, not fetched — so the corpus is hermetic and free of the Argon
# redistribution constraint.
#
# Pins are generated with the ASM build (`--features asm` = dav1d's
# hand-written assembly), so the manifest is a dav1d-parity oracle, not a
# self-consistency check: a regression in ANY tier — scalar included — fails
# against it.
#
# Usage:
#   scripts/gen_vectors.sh
#
# Env:
#   ZENAV1_SVT   path to the zenav1-svt checkout (default: ../zenav1-svt)
#
# Committing: regenerate streams+manifest together and commit both; the pins
# encode the behavior of the zenav1-svt commit that produced them, so bump
# the pair atomically when the encoder output changes.

set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ZENAV1_SVT="${ZENAV1_SVT:-$ROOT/../zenav1-svt}"
OUT="$ROOT/tests/gen_vectors"
MANIFEST="$ROOT/tests/gen_vectors_manifest.tsv"

if [ ! -f "$ZENAV1_SVT/rust/Cargo.toml" ]; then
    echo "zenav1-svt checkout not found at $ZENAV1_SVT (set ZENAV1_SVT)" >&2
    exit 1
fi

echo "== encoding matrix via zenav1-svt gen_cover =="
cargo run --release --manifest-path "$ZENAV1_SVT/rust/Cargo.toml" \
    -p zenav1-svt --example gen_cover -- "$OUT"

echo "== building asm-oracle decode_md5 =="
cargo build --release --manifest-path "$ROOT/Cargo.toml" \
    --features "asm,bitdepth_8,bitdepth_16" --example decode_md5
BIN="$ROOT/target/release/examples/decode_md5"

# decode_md5 prints the stream md5 as its last 32-hex line; run twice per
# stream — default (no film-grain synthesis) and --filmgrain — matching the
# Argon md5_no_film_grain / md5_ref sidecar split.
md5_of() { "$BIN" "$@" | grep -E '^[0-9a-f]{32}$' | tail -1; }

printf '# generated by scripts/gen_vectors.sh — asm-build pins; regenerate and commit together\n' > "$MANIFEST"
printf 'name\tbytes\tmd5_no_film_grain\tmd5_ref\n' >> "$MANIFEST"
count=0
for f in "$OUT"/*.obu; do
    name=$(basename "$f" .obu)
    bytes=$(stat -c%s "$f")
    printf '%s\t%s\t%s\t%s\n' "$name" "$bytes" \
        "$(md5_of "$f")" "$(md5_of --filmgrain "$f")" >> "$MANIFEST"
    count=$((count + 1))
done
echo "wrote $MANIFEST ($count vectors)"
